#!/bin/bash
# -----------------------------
# Interactive Notification Template Creator
# -----------------------------
# Creates a new notification config file step by step
# Empty input will use default values
# The resulting file is saved in current user directory
# -----------------------------

# Default values
DEFAULT_NOTIFICATION_ENABLED="true"
DEFAULT_TITLE="New Notification"
DEFAULT_BODY="This is a notification"
DEFAULT_ICON="dialog-information"
DEFAULT_URGENCY="normal"
DEFAULT_TIMEOUT="5000"
DEFAULT_TRANSIENT="true"
DEFAULT_SOUND_ENABLED="true"
DEFAULT_SOUND="/usr/share/sounds/freedesktop/stereo/service-logout.oga"
DEFAULT_REPEAT="1"
DEFAULT_SLEEP="0"

read -p "Display Notification? (true/false) [$DEFAULT_NOTIFICATION_ENABLED]: " NOTIFICATION_ENABLED
NOTIFICATION_ENABLED=${NOTIFICATION_ENABLED:-$DEFAULT_NOTIFICATION_ENABLED}

if [[ "$NOTIFICATION_ENABLED" == "true" ]]; then

	read -p "Title [$DEFAULT_TITLE]: " TITLE
	TITLE=${TITLE:-$DEFAULT_TITLE}

	read -p "Body [$DEFAULT_BODY]: " BODY
	BODY=${BODY:-$DEFAULT_BODY}

	read -p "Icon (optional) [$DEFAULT_ICON]: " ICON
	ICON=${ICON:-$DEFAULT_ICON}

	read -p "Urgency (low/normal/critical) [$DEFAULT_URGENCY]: " URGENCY
	URGENCY=${URGENCY:-$DEFAULT_URGENCY}

	read -p "Timeout in ms [$DEFAULT_TIMEOUT]: " TIMEOUT
	TIMEOUT=${TIMEOUT:-$DEFAULT_TIMEOUT}

	read -p "Transient (true/false) [$DEFAULT_TRANSIENT]: " TRANSIENT
	TRANSIENT=${TRANSIENT:-$DEFAULT_TRANSIENT}
	
	else
	    TIMEOUT="5000"
	    TITLE=""
	    BODY=""	    
	    TRANSIENT="true"
	    ICON=""
	    URGENCY="normal"
fi

read -p "Play sound? (true/false) [$DEFAULT_SOUND_ENABLED]: " SOUND_ENABLED
SOUND_ENABLED=${SOUND_ENABLED:-$DEFAULT_SOUND_ENABLED}

if [[ "$SOUND_ENABLED" == "true" ]]; then
    read -p "Sound file path [$DEFAULT_SOUND]: " SOUND
    SOUND=${SOUND:-$DEFAULT_SOUND}

    read -p "Repeat times [$DEFAULT_REPEAT]: " REPEAT
    REPEAT=${REPEAT:-$DEFAULT_REPEAT}

    read -p "Sleep between repeats (seconds) [$DEFAULT_SLEEP]: " SLEEP
    SLEEP=${SLEEP:-$DEFAULT_SLEEP}
else
    SOUND=""
    REPEAT="1"
    SLEEP="0"
fi

# Ask for filename and location
read -p "Filename (without extension) [notification]: " FILENAME
FILENAME=${FILENAME:-notification}

read -p "Save to directory [current directory]: " TARGET_DIR
TARGET_DIR=${TARGET_DIR:-$PWD}

# Create directory if it doesn't exist
mkdir -p "$TARGET_DIR" 2>/dev/null || {
    echo "ERROR: Cannot create directory: $TARGET_DIR" >&2
    exit 1
}

TARGET_FILE="$TARGET_DIR/$FILENAME.conf"

echo "Notification config created: $TARGET_FILE"
echo "You can modify it manually"
echo "To test: echo '$FILENAME.conf' | nc localhost ${NOTIFICATION_PORT:-52346}"
echo "Or copy to /etc/fast-notification/ for system-wide use"

# Write config
cat > "$TARGET_FILE" <<EOL
# Notification Configuration Template
# ----------------------------------
# This file defines parameters for a desktop notification
# Generated By fast-notification-service

[notification]
# Is the notification enabled - true or false
notification_enabled=$NOTIFICATION_ENABLED
# Title of the notification
title=$TITLE
# Body text / message
body=$BODY
# Icon (optional)
icon=$ICON
# Urgency: low, normal, critical
urgency=$URGENCY
# Timeout in milliseconds (0 = persistent)
timeout=$TIMEOUT
# Transient (true/false)
transient=$TRANSIENT

[sound]
# sound is enabled (true/false)
sound_enabled=$SOUND_ENABLED
# Path to sound file (optional)
file=$SOUND
# How many times to repeat the sound
repeat=$REPEAT
# Delay in seconds between repeats
sleep=$SLEEP
EOL

